services:
  postgres:
    image: postgres:17
    container_name: fusionpbx_postgres
    environment:
      POSTGRES_USER: fusionpbx
      POSTGRES_PASSWORD: password123
      POSTGRES_DB: fusionpbx
    volumes:
      - ./data/postgres:/var/lib/postgresql/data
    networks:
      - fusionpbx_net

  fusionpbx:
    build: ./fusionpbx
    container_name: fusionpbx_app
    volumes:
      - fusionpbx_data:/var/www/fusionpbx
    depends_on:
      - postgres
    networks:
      - fusionpbx_net

  freeswitch:
    build: ./freeswitch
    container_name: fusionpbx_freeswitch
    volumes:
      - fusionpbx_data:/var/www/fusionpbx
      - freeswitch_data:/usr/local/freeswitch
    depends_on:
      - postgres
      - fusionpbx
    ports:
      - "5060:5060/tcp"
      - "5060:5060/udp"
      - "5080:5080/tcp"
      - "5080:5080/udp"
      - "8022:8021/tcp"
      - "16384-16394:16384-16394/udp"
    networks:
      - fusionpbx_net

  nginx:
    image: nginx:latest
    container_name: fusionpbx_nginx
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf:ro
      - fusionpbx_data:/var/www/fusionpbx:ro
    depends_on:
      - fusionpbx
    networks:
      - fusionpbx_net

volumes:
  fusionpbx_data:
  freeswitch_data:

networks:
  fusionpbx_net:
    driver: bridge
